"""Add missing columns to drivers table

Revision ID: 12e662681499
Revises: 8a1e4fbb9624
Create Date: 2025-05-13 14:46:22.781279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12e662681499'
down_revision = '8a1e4fbb9624'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_users', sa.Column('confirmation_code', sa.String(), nullable=True))
    op.add_column('driver_users', sa.Column('code_expiry', sa.DateTime(), nullable=True))
    op.add_column('driver_users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('driver_users', 'phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index('ix_driver_users_phone', table_name='driver_users')
    op.create_unique_constraint(None, 'driver_users', ['phone'])
    op.add_column('drivers', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('drivers', sa.Column('is_online', sa.Boolean(), nullable=True))
    op.add_column('drivers', sa.Column('last_online', sa.DateTime(), nullable=True))
    op.add_column('drivers', sa.Column('tariff_id', sa.Integer(), nullable=True))
    op.add_column('drivers', sa.Column('autopark_id', sa.Integer(), nullable=True))
    op.add_column('drivers', sa.Column('personal_number', sa.String(), nullable=True))
    op.add_column('drivers', sa.Column('birth_date', sa.String(), nullable=True))
    op.add_column('drivers', sa.Column('address', sa.String(), nullable=True))
    op.add_column('drivers', sa.Column('driver_license', sa.String(), nullable=True))
    op.add_column('drivers', sa.Column('license_issue_date', sa.String(), nullable=True))
    op.add_column('drivers', sa.Column('license_expiry_date', sa.String(), nullable=True))
    op.alter_column('drivers', 'callsign',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('drivers', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('drivers', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('drivers', 'rating',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_constraint('drivers_driver_license_number_key', 'drivers', type_='unique')
    op.drop_index('ix_drivers_unique_id', table_name='drivers')
    op.create_index(op.f('ix_drivers_callsign'), 'drivers', ['callsign'], unique=True)
    op.create_foreign_key(None, 'drivers', 'tariffs', ['tariff_id'], ['id'])
    op.create_foreign_key(None, 'drivers', 'autoparks', ['autopark_id'], ['id'])
    op.drop_column('drivers', 'tariff')
    op.drop_column('drivers', 'taxi_park')
    op.drop_column('drivers', 'activity')
    op.drop_column('drivers', 'driver_license_number')
    op.drop_column('drivers', 'unique_id')
    op.drop_column('drivers', 'driver_license_issue_date')
    op.drop_column('drivers', 'birthdate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('birthdate', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('drivers', sa.Column('driver_license_issue_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('drivers', sa.Column('unique_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('drivers', sa.Column('driver_license_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('drivers', sa.Column('activity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('drivers', sa.Column('taxi_park', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('drivers', sa.Column('tariff', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.drop_index(op.f('ix_drivers_callsign'), table_name='drivers')
    op.create_index('ix_drivers_unique_id', 'drivers', ['unique_id'], unique=False)
    op.create_unique_constraint('drivers_driver_license_number_key', 'drivers', ['driver_license_number'])
    op.alter_column('drivers', 'rating',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('drivers', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('drivers', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('drivers', 'callsign',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('drivers', 'license_expiry_date')
    op.drop_column('drivers', 'license_issue_date')
    op.drop_column('drivers', 'driver_license')
    op.drop_column('drivers', 'address')
    op.drop_column('drivers', 'birth_date')
    op.drop_column('drivers', 'personal_number')
    op.drop_column('drivers', 'autopark_id')
    op.drop_column('drivers', 'tariff_id')
    op.drop_column('drivers', 'last_online')
    op.drop_column('drivers', 'is_online')
    op.drop_column('drivers', 'created_at')
    op.drop_constraint(None, 'driver_users', type_='unique')
    op.create_index('ix_driver_users_phone', 'driver_users', ['phone'], unique=False)
    op.alter_column('driver_users', 'phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('driver_users', 'created_at')
    op.drop_column('driver_users', 'code_expiry')
    op.drop_column('driver_users', 'confirmation_code')
    # ### end Alembic commands ### 