"""add_activity_rating_to_driver

Revision ID: 3feaef660364
Revises: e13021fba454
Create Date: 2025-05-12 20:52:47.758471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3feaef660364'
down_revision = 'e13021fba454'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('activity', sa.Integer(), nullable=True))
    op.add_column('drivers', sa.Column('rating', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drivers', 'rating')
    op.drop_column('drivers', 'activity')
    # ### end Alembic commands ### 