"""Add order_number and tariff to orders

Revision ID: 75b9c66cbd9d
Revises: aa9ac8cf0ba1
Create Date: 2025-08-13 03:43:52.150628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75b9c66cbd9d'
down_revision = 'aa9ac8cf0ba1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_number', sa.String(length=20), nullable=False))
    op.add_column('orders', sa.Column('tariff', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'orders', ['order_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_column('orders', 'tariff')
    op.drop_column('orders', 'order_number')
    # ### end Alembic commands ### 