"""add_sticker_lightbox_columns

Revision ID: 8a1e4fbb9624
Revises: 3feaef660364
Create Date: 2025-05-13 11:26:19.151282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a1e4fbb9624'
down_revision = '3feaef660364'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('has_sticker', sa.Boolean(), nullable=True))
    op.add_column('cars', sa.Column('has_lightbox', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'has_lightbox')
    op.drop_column('cars', 'has_sticker')
    # ### end Alembic commands ### 