"""Add status field to Driver model

Revision ID: 96606c91e336
Revises: 42a708ee1f84
Create Date: 2025-04-19 15:39:04.459970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96606c91e336'
down_revision = '42a708ee1f84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('status', sa.String(length=20), nullable=True))
    op.alter_column('drivers', 'driver_license_issue_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drivers', 'driver_license_issue_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('drivers', 'status')
    # ### end Alembic commands ### 