"""increase_time_field_length_for_seconds

Revision ID: d55459031a7e
Revises: 75b9c66cbd9d
Create Date: 2025-08-14 02:05:48.738672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd55459031a7e'
down_revision = '75b9c66cbd9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Увеличиваем длину поля time с 5 до 8 символов для поддержки формата ЧЧ:ММ:СС
    op.alter_column('orders', 'time',
                    existing_type=sa.String(length=5),
                    type_=sa.String(length=8),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Возвращаем обратно к 5 символам (ЧЧ:ММ)
    op.alter_column('orders', 'time',
                    existing_type=sa.String(length=8),
                    type_=sa.String(length=5),
                    existing_nullable=False)
    # ### end Alembic commands ### 