"""add_order_progress_tracking_fields

Revision ID: e50a84499425
Revises: d55459031a7e
Create Date: 2025-08-24 00:10:58.243122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e50a84499425'
down_revision = 'd55459031a7e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('current_lat', sa.Float(), nullable=True))
    op.add_column('drivers', sa.Column('current_lng', sa.Float(), nullable=True))
    op.add_column('drivers', sa.Column('last_location_update', sa.DateTime(), nullable=True))
    op.add_column('drivers', sa.Column('is_online', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('origin_lat', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('origin_lng', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('destination_lat', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('destination_lng', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('total_distance', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('completed_distance', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('progress_percentage', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('actual_price', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'completed_at')
    op.drop_column('orders', 'started_at')
    op.drop_column('orders', 'actual_price')
    op.drop_column('orders', 'progress_percentage')
    op.drop_column('orders', 'completed_distance')
    op.drop_column('orders', 'total_distance')
    op.drop_column('orders', 'destination_lng')
    op.drop_column('orders', 'destination_lat')
    op.drop_column('orders', 'origin_lng')
    op.drop_column('orders', 'origin_lat')
    op.drop_column('drivers', 'is_online')
    op.drop_column('drivers', 'last_location_update')
    op.drop_column('drivers', 'current_lng')
    op.drop_column('drivers', 'current_lat')
    # ### end Alembic commands ### 