"""Add photos column to driver_verifications table

Revision ID: f5e3d6f39600
Revises: 12e662681499
Create Date: 2025-05-13 15:13:26.534661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5e3d6f39600'
down_revision = '12e662681499'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_verifications', sa.Column('photos', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver_verifications', 'photos')
    # ### end Alembic commands ### 